### ISSUE TITLE
Commas in data

### ISSUE THREAD

**Issue by jesper-predictly** [AyQWERTY/WarThunder-Tanks-Scraper#1]
The BRs are expressed as "9,7" which messes up the CSV completely. It needs to be escaped, replaced or otherwise.

```
Name,Nation,Rank,Rating,...
2S38,USSR,VI,"9,7",...
```

**Comment by AyQWERTY** [comment]
I disagree. Since the text is written in quotes, it does not break the csv structure. I checked both in VS Code and Excel. Columns are correctly detected and read everywhere.

The reason for this comma: when importing into Excel, the decimal part is separated by a comma, so I [intentionally replaced](https://github.com/AyQWERTY/WarThunder-Tanks-Scraper/blob/5d139343ccf126bcbdf70ee396b41a0e43092770/scraper/scraper.py#L33) the dot with a comma, because the dot turns the value into a "Text" type.

**Comment by jesper-predictly** [comment]
Ah ok, I was reading it programmatically and the lib I used didn't work with quotation marks.
